# Generated by Django 5.2.7 on 2025-10-26 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publication_year',
            new_name='publication_date',
        ),
    ]
